#!/bin/bash
sudo apt-get install apache2 -y
sudo add-apt-repository ppa:ondrej/php
sudo apt install software-properties-common
sudo apt-get install php8.0 libapache2-mod-php8.0 php8.0-phpdbg php8.0-fpm php8.0-cli php8.0-cgi libphp8.0-embed php8.0-curl php8.0-imap php8.0-gd php8.0-mysql php8.0-pgsql php8.0-sqlite3 php8.0-mbstring php8.0-bz2 php8.0-xmlrpc php8.0-gmp php8.0-xsl php8.0-soap php8.0-xml php8.0-zip php8.0-dba -y
sudo cp -rvf dir.conf /etc/apache2/mods-enabled/dir.conf
sudo apt-get install mysql-server mysql-client -y
apt-get install phpmyadmin php-mbstring -y
sudo mysql -u root -e "create user 'carrental'@'localhost' identified by 'Carrental@123';"
sudo mysql -u root -e "create database carrental;"
sudo mysql -u root -e "grant all privileges on carrental.*to'carrental'@'localhost';"
sudo mysql -u root -e "flush privileges"
sudo mysql -u root carrental < /var/www/html/carrental/sqlfile/carrental.sql